sudo: false
language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

before_script:
  - npm ci

script:
  - npm run build

deploy:
  - provider: pages
    github-token: "$GITHUB_TOKEN"
    skip-cleanup: true
    local-dir: "public"
    keep-history: true
    on:
      branch: master
      node_js: "10"
